import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import Footer from "../components/Footer";
import "./globals.css";
// import { courierPrimeFont } from "@/lib/fonts";
import { courierPrimeFont, notoSans } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${courierPrimeFont.variable} ${notoSans.variable}`}>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
